# Only allow import of papers below the specified MAX character count
MAX_LATEX_CHARACTER_COUNT = 300000

ARXIV_ID_MAX_LENGTH = 20
MAX_QUERY_LENGTH = 1000
MAX_HIGHLIGHT_LENGTH = 100000
MAX_USER_FEEDBACK_LENGTH = 1000

PLACEHOLDER_PREFIX = "[[LUMI_PLACEHOLDER_"
PLACEHOLDER_SUFFIX = "]]"
EQUATION_PLACEHOLDER_PREFIX = "[[LUMI_EQUATION_"

# Keep in sync with constants.ts
PERSONAL_SUMMARY_QUERY_NAME = "Summarize this paper"
CONCEPT_CONTENT_LABEL_DEFINITION = "definition"
CONCEPT_CONTENT_LABEL_RELEVANCE = "relevance"
